// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Synchro_Slave.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Synchro_Slave.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Docapost {
namespace IA {
namespace Tesseract {
namespace Proto {

namespace {

const ::google::protobuf::Descriptor* Synchro_Slave_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Synchro_Slave_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Synchro_5fSlave_2eproto() {
  protobuf_AddDesc_Synchro_5fSlave_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Synchro_Slave.proto");
  GOOGLE_CHECK(file != NULL);
  Synchro_Slave_descriptor_ = file->message_type(0);
  static const int Synchro_Slave_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Synchro_Slave, threadrunning_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Synchro_Slave, nbfilesrequired_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Synchro_Slave, data_),
  };
  Synchro_Slave_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Synchro_Slave_descriptor_,
      Synchro_Slave::default_instance_,
      Synchro_Slave_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Synchro_Slave, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Synchro_Slave, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Synchro_Slave));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Synchro_5fSlave_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Synchro_Slave_descriptor_, &Synchro_Slave::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Synchro_5fSlave_2eproto() {
  delete Synchro_Slave::default_instance_;
  delete Synchro_Slave_reflection_;
}

void protobuf_AddDesc_Synchro_5fSlave_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Docapost::IA::Tesseract::Proto::protobuf_AddDesc_Result_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023Synchro_Slave.proto\022\033Docapost.IA.Tesse"
    "ract.Proto\032\014Result.proto\"r\n\rSynchro_Slav"
    "e\022\025\n\rThreadRunning\030\001 \002(\005\022\027\n\017NbFilesRequi"
    "red\030\002 \001(\005\0221\n\004Data\030\003 \003(\0132#.Docapost.IA.Te"
    "sseract.Proto.Result", 180);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Synchro_Slave.proto", &protobuf_RegisterTypes);
  Synchro_Slave::default_instance_ = new Synchro_Slave();
  Synchro_Slave::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Synchro_5fSlave_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Synchro_5fSlave_2eproto {
  StaticDescriptorInitializer_Synchro_5fSlave_2eproto() {
    protobuf_AddDesc_Synchro_5fSlave_2eproto();
  }
} static_descriptor_initializer_Synchro_5fSlave_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Synchro_Slave::kThreadRunningFieldNumber;
const int Synchro_Slave::kNbFilesRequiredFieldNumber;
const int Synchro_Slave::kDataFieldNumber;
#endif  // !_MSC_VER

Synchro_Slave::Synchro_Slave()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Docapost.IA.Tesseract.Proto.Synchro_Slave)
}

void Synchro_Slave::InitAsDefaultInstance() {
}

Synchro_Slave::Synchro_Slave(const Synchro_Slave& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Docapost.IA.Tesseract.Proto.Synchro_Slave)
}

void Synchro_Slave::SharedCtor() {
  _cached_size_ = 0;
  threadrunning_ = 0;
  nbfilesrequired_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Synchro_Slave::~Synchro_Slave() {
  // @@protoc_insertion_point(destructor:Docapost.IA.Tesseract.Proto.Synchro_Slave)
  SharedDtor();
}

void Synchro_Slave::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Synchro_Slave::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Synchro_Slave::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Synchro_Slave_descriptor_;
}

const Synchro_Slave& Synchro_Slave::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Synchro_5fSlave_2eproto();
  return *default_instance_;
}

Synchro_Slave* Synchro_Slave::default_instance_ = NULL;

Synchro_Slave* Synchro_Slave::New() const {
  return new Synchro_Slave;
}

void Synchro_Slave::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Synchro_Slave*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(threadrunning_, nbfilesrequired_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  data_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Synchro_Slave::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Docapost.IA.Tesseract.Proto.Synchro_Slave)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 ThreadRunning = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &threadrunning_)));
          set_has_threadrunning();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_NbFilesRequired;
        break;
      }

      // optional int32 NbFilesRequired = 2;
      case 2: {
        if (tag == 16) {
         parse_NbFilesRequired:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nbfilesrequired_)));
          set_has_nbfilesrequired();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_Data;
        break;
      }

      // repeated .Docapost.IA.Tesseract.Proto.Result Data = 3;
      case 3: {
        if (tag == 26) {
         parse_Data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_Data;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Docapost.IA.Tesseract.Proto.Synchro_Slave)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Docapost.IA.Tesseract.Proto.Synchro_Slave)
  return false;
#undef DO_
}

void Synchro_Slave::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Docapost.IA.Tesseract.Proto.Synchro_Slave)
  // required int32 ThreadRunning = 1;
  if (has_threadrunning()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->threadrunning(), output);
  }

  // optional int32 NbFilesRequired = 2;
  if (has_nbfilesrequired()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->nbfilesrequired(), output);
  }

  // repeated .Docapost.IA.Tesseract.Proto.Result Data = 3;
  for (int i = 0; i < this->data_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->data(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Docapost.IA.Tesseract.Proto.Synchro_Slave)
}

::google::protobuf::uint8* Synchro_Slave::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Docapost.IA.Tesseract.Proto.Synchro_Slave)
  // required int32 ThreadRunning = 1;
  if (has_threadrunning()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->threadrunning(), target);
  }

  // optional int32 NbFilesRequired = 2;
  if (has_nbfilesrequired()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->nbfilesrequired(), target);
  }

  // repeated .Docapost.IA.Tesseract.Proto.Result Data = 3;
  for (int i = 0; i < this->data_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->data(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Docapost.IA.Tesseract.Proto.Synchro_Slave)
  return target;
}

int Synchro_Slave::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 ThreadRunning = 1;
    if (has_threadrunning()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->threadrunning());
    }

    // optional int32 NbFilesRequired = 2;
    if (has_nbfilesrequired()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nbfilesrequired());
    }

  }
  // repeated .Docapost.IA.Tesseract.Proto.Result Data = 3;
  total_size += 1 * this->data_size();
  for (int i = 0; i < this->data_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->data(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Synchro_Slave::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Synchro_Slave* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Synchro_Slave*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Synchro_Slave::MergeFrom(const Synchro_Slave& from) {
  GOOGLE_CHECK_NE(&from, this);
  data_.MergeFrom(from.data_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_threadrunning()) {
      set_threadrunning(from.threadrunning());
    }
    if (from.has_nbfilesrequired()) {
      set_nbfilesrequired(from.nbfilesrequired());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Synchro_Slave::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Synchro_Slave::CopyFrom(const Synchro_Slave& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Synchro_Slave::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->data())) return false;
  return true;
}

void Synchro_Slave::Swap(Synchro_Slave* other) {
  if (other != this) {
    std::swap(threadrunning_, other->threadrunning_);
    std::swap(nbfilesrequired_, other->nbfilesrequired_);
    data_.Swap(&other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Synchro_Slave::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Synchro_Slave_descriptor_;
  metadata.reflection = Synchro_Slave_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Tesseract
}  // namespace IA
}  // namespace Docapost

// @@protoc_insertion_point(global_scope)
