// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Declare.proto

#ifndef PROTOBUF_Declare_2eproto__INCLUDED
#define PROTOBUF_Declare_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Docapost {
namespace IA {
namespace Tesseract {
namespace Proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Declare_2eproto();
void protobuf_AssignDesc_Declare_2eproto();
void protobuf_ShutdownFile_Declare_2eproto();

class Declare;

// ===================================================================

class Declare : public ::google::protobuf::Message {
 public:
  Declare();
  virtual ~Declare();

  Declare(const Declare& from);

  inline Declare& operator=(const Declare& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Declare& default_instance();

  void Swap(Declare* other);

  // implements Message ----------------------------------------------

  Declare* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Declare& from);
  void MergeFrom(const Declare& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 Thread = 1;
  inline bool has_thread() const;
  inline void clear_thread();
  static const int kThreadFieldNumber = 1;
  inline ::google::protobuf::int32 thread() const;
  inline void set_thread(::google::protobuf::int32 value);

  // required string Hostname = 2;
  inline bool has_hostname() const;
  inline void clear_hostname();
  static const int kHostnameFieldNumber = 2;
  inline const ::std::string& hostname() const;
  inline void set_hostname(const ::std::string& value);
  inline void set_hostname(const char* value);
  inline void set_hostname(const char* value, size_t size);
  inline ::std::string* mutable_hostname();
  inline ::std::string* release_hostname();
  inline void set_allocated_hostname(::std::string* hostname);

  // @@protoc_insertion_point(class_scope:Docapost.IA.Tesseract.Proto.Declare)
 private:
  inline void set_has_thread();
  inline void clear_has_thread();
  inline void set_has_hostname();
  inline void clear_has_hostname();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* hostname_;
  ::google::protobuf::int32 thread_;
  friend void  protobuf_AddDesc_Declare_2eproto();
  friend void protobuf_AssignDesc_Declare_2eproto();
  friend void protobuf_ShutdownFile_Declare_2eproto();

  void InitAsDefaultInstance();
  static Declare* default_instance_;
};
// ===================================================================


// ===================================================================

// Declare

// required int32 Thread = 1;
inline bool Declare::has_thread() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Declare::set_has_thread() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Declare::clear_has_thread() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Declare::clear_thread() {
  thread_ = 0;
  clear_has_thread();
}
inline ::google::protobuf::int32 Declare::thread() const {
  // @@protoc_insertion_point(field_get:Docapost.IA.Tesseract.Proto.Declare.Thread)
  return thread_;
}
inline void Declare::set_thread(::google::protobuf::int32 value) {
  set_has_thread();
  thread_ = value;
  // @@protoc_insertion_point(field_set:Docapost.IA.Tesseract.Proto.Declare.Thread)
}

// required string Hostname = 2;
inline bool Declare::has_hostname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Declare::set_has_hostname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Declare::clear_has_hostname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Declare::clear_hostname() {
  if (hostname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hostname_->clear();
  }
  clear_has_hostname();
}
inline const ::std::string& Declare::hostname() const {
  // @@protoc_insertion_point(field_get:Docapost.IA.Tesseract.Proto.Declare.Hostname)
  return *hostname_;
}
inline void Declare::set_hostname(const ::std::string& value) {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hostname_ = new ::std::string;
  }
  hostname_->assign(value);
  // @@protoc_insertion_point(field_set:Docapost.IA.Tesseract.Proto.Declare.Hostname)
}
inline void Declare::set_hostname(const char* value) {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hostname_ = new ::std::string;
  }
  hostname_->assign(value);
  // @@protoc_insertion_point(field_set_char:Docapost.IA.Tesseract.Proto.Declare.Hostname)
}
inline void Declare::set_hostname(const char* value, size_t size) {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hostname_ = new ::std::string;
  }
  hostname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Docapost.IA.Tesseract.Proto.Declare.Hostname)
}
inline ::std::string* Declare::mutable_hostname() {
  set_has_hostname();
  if (hostname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    hostname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Docapost.IA.Tesseract.Proto.Declare.Hostname)
  return hostname_;
}
inline ::std::string* Declare::release_hostname() {
  clear_has_hostname();
  if (hostname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = hostname_;
    hostname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Declare::set_allocated_hostname(::std::string* hostname) {
  if (hostname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete hostname_;
  }
  if (hostname) {
    set_has_hostname();
    hostname_ = hostname;
  } else {
    clear_has_hostname();
    hostname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Docapost.IA.Tesseract.Proto.Declare.Hostname)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Tesseract
}  // namespace IA
}  // namespace Docapost

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Declare_2eproto__INCLUDED
