// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message_Master.proto

#ifndef PROTOBUF_Message_5fMaster_2eproto__INCLUDED
#define PROTOBUF_Message_5fMaster_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Synchro_Master.pb.h"
#include "Status.pb.h"
// @@protoc_insertion_point(includes)

namespace Docapost {
namespace IA {
namespace Tesseract {
namespace Proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Message_5fMaster_2eproto();
void protobuf_AssignDesc_Message_5fMaster_2eproto();
void protobuf_ShutdownFile_Message_5fMaster_2eproto();

class Message_Master;

// ===================================================================

class Message_Master : public ::google::protobuf::Message {
 public:
  Message_Master();
  virtual ~Message_Master();

  Message_Master(const Message_Master& from);

  inline Message_Master& operator=(const Message_Master& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message_Master& default_instance();

  enum MessageCase {
    kSynchro = 1,
    kStatus = 2,
    MESSAGE_NOT_SET = 0,
  };

  void Swap(Message_Master* other);

  // implements Message ----------------------------------------------

  Message_Master* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message_Master& from);
  void MergeFrom(const Message_Master& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Docapost.IA.Tesseract.Proto.Synchro_Master synchro = 1;
  inline bool has_synchro() const;
  inline void clear_synchro();
  static const int kSynchroFieldNumber = 1;
  inline const ::Docapost::IA::Tesseract::Proto::Synchro_Master& synchro() const;
  inline ::Docapost::IA::Tesseract::Proto::Synchro_Master* mutable_synchro();
  inline ::Docapost::IA::Tesseract::Proto::Synchro_Master* release_synchro();
  inline void set_allocated_synchro(::Docapost::IA::Tesseract::Proto::Synchro_Master* synchro);

  // optional .Docapost.IA.Tesseract.Proto.Status status = 2;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 2;
  inline const ::Docapost::IA::Tesseract::Proto::Status& status() const;
  inline ::Docapost::IA::Tesseract::Proto::Status* mutable_status();
  inline ::Docapost::IA::Tesseract::Proto::Status* release_status();
  inline void set_allocated_status(::Docapost::IA::Tesseract::Proto::Status* status);

  inline MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:Docapost.IA.Tesseract.Proto.Message_Master)
 private:
  inline void set_has_synchro();
  inline void set_has_status();

  inline bool has_message();
  void clear_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  union MessageUnion {
    ::Docapost::IA::Tesseract::Proto::Synchro_Master* synchro_;
    ::Docapost::IA::Tesseract::Proto::Status* status_;
  } message_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_Message_5fMaster_2eproto();
  friend void protobuf_AssignDesc_Message_5fMaster_2eproto();
  friend void protobuf_ShutdownFile_Message_5fMaster_2eproto();

  void InitAsDefaultInstance();
  static Message_Master* default_instance_;
};
// ===================================================================


// ===================================================================

// Message_Master

// optional .Docapost.IA.Tesseract.Proto.Synchro_Master synchro = 1;
inline bool Message_Master::has_synchro() const {
  return message_case() == kSynchro;
}
inline void Message_Master::set_has_synchro() {
  _oneof_case_[0] = kSynchro;
}
inline void Message_Master::clear_synchro() {
  if (has_synchro()) {
    delete message_.synchro_;
    clear_has_message();
  }
}
inline const ::Docapost::IA::Tesseract::Proto::Synchro_Master& Message_Master::synchro() const {
  return has_synchro() ? *message_.synchro_
                      : ::Docapost::IA::Tesseract::Proto::Synchro_Master::default_instance();
}
inline ::Docapost::IA::Tesseract::Proto::Synchro_Master* Message_Master::mutable_synchro() {
  if (!has_synchro()) {
    clear_message();
    set_has_synchro();
    message_.synchro_ = new ::Docapost::IA::Tesseract::Proto::Synchro_Master;
  }
  return message_.synchro_;
}
inline ::Docapost::IA::Tesseract::Proto::Synchro_Master* Message_Master::release_synchro() {
  if (has_synchro()) {
    clear_has_message();
    ::Docapost::IA::Tesseract::Proto::Synchro_Master* temp = message_.synchro_;
    message_.synchro_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Message_Master::set_allocated_synchro(::Docapost::IA::Tesseract::Proto::Synchro_Master* synchro) {
  clear_message();
  if (synchro) {
    set_has_synchro();
    message_.synchro_ = synchro;
  }
}

// optional .Docapost.IA.Tesseract.Proto.Status status = 2;
inline bool Message_Master::has_status() const {
  return message_case() == kStatus;
}
inline void Message_Master::set_has_status() {
  _oneof_case_[0] = kStatus;
}
inline void Message_Master::clear_status() {
  if (has_status()) {
    delete message_.status_;
    clear_has_message();
  }
}
inline const ::Docapost::IA::Tesseract::Proto::Status& Message_Master::status() const {
  return has_status() ? *message_.status_
                      : ::Docapost::IA::Tesseract::Proto::Status::default_instance();
}
inline ::Docapost::IA::Tesseract::Proto::Status* Message_Master::mutable_status() {
  if (!has_status()) {
    clear_message();
    set_has_status();
    message_.status_ = new ::Docapost::IA::Tesseract::Proto::Status;
  }
  return message_.status_;
}
inline ::Docapost::IA::Tesseract::Proto::Status* Message_Master::release_status() {
  if (has_status()) {
    clear_has_message();
    ::Docapost::IA::Tesseract::Proto::Status* temp = message_.status_;
    message_.status_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Message_Master::set_allocated_status(::Docapost::IA::Tesseract::Proto::Status* status) {
  clear_message();
  if (status) {
    set_has_status();
    message_.status_ = status;
  }
}

inline bool Message_Master::has_message() {
  return message_case() != MESSAGE_NOT_SET;
}
inline void Message_Master::clear_has_message() {
  _oneof_case_[0] = MESSAGE_NOT_SET;
}
inline Message_Master::MessageCase Message_Master::message_case() const {
  return Message_Master::MessageCase(_oneof_case_[0]);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Tesseract
}  // namespace IA
}  // namespace Docapost

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Message_5fMaster_2eproto__INCLUDED
